sudo: false
language: node_js
node_js:
  - '8'
script:
  - rm -rf node_modules
  - npm install
  - npm run build
  - npm run test

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  on:
    tags: true
  # make sure we keep our dist directory
  skip_cleanup: true
